### ISSUE TITLE
Write a Readme.md  attractive

### ISSUE THREAD

**Issue by dieram3** [dieram3/competitive-programming-library#10]
We need a readme.md to generate enthusiasm to the readers. It must explain usage, quick start, example, installation, how to submit a proposal, etc.

**Comment by jaguirresza** [comment]
I can do that, i don't know why but i love to write in markdown jajaja.

**Comment by dieram3** [comment]
Ok, that's great :)

**Comment by dieram3** [comment]
Sorry but I could wait more for an attractive README file so I wrote one. But it is a first glance, it is expected to be improved with the time :)
