### ISSUE TITLE
Someone have to add the missing tests

### ISSUE THREAD

**Issue by jaguirresza** [dieram3/competitive-programming-library#12]
So far missing tests are:
- [x] `adjacency_list_test.cpp`
- [x] `fenwick_tree_test.cpp`
- [x] `iterator_range_test.cpp`
- [x] `matrix_test.cpp`

**Comment by dieram3** [comment]
I will do this.

**Comment by dieram3** [comment]
I just added fenwick tree test

**Comment by jaguirresza** [comment]
look! it's possible to add tasks lists!!

**Comment by dieram3** [comment]
Great! Now only 3 test are missing :)

**Comment by dieram3** [comment]
Done!
