### ISSUE TITLE
convex_hull revision

### ISSUE THREAD

**Issue by dieram3** [dieram3/competitive-programming-library#14]
I think that the convex_hull interface could be cumbersome to use in some case, and it is not trivial to understand how the clockwise functor should work, so this could generate errors.

What if we had something like this:

```
make_convex_hull(points, with_collinear_points) -> convex_hull
make_convex_hull(points, without_collinear_points) -> convex_hull
```

This is trivial to use, and I think that satisfy the problem in most of cases.

Of course, optimized versions stand as always.

**Comment by jaguirresza** [comment]
ok

**Comment by jaguirresza** [comment]
Now that i think a little bit more, i don't think that a higher level interface is a good idea. Because this will be dependant of point class implementation.
What we can do is improve documentation and the commentaries of the tests in a way that make obvious the usage of the actual implementations.

**Comment by jaguirresza** [comment]
I add some changes to `make_convex_set` in 8da062c. I think that with those now the interface of `convex_hull` and  `convex_hull_partition` its more intuitive.

**Comment by dieram3** [comment]
What's the change? In addition to change cw to ccw...
