### ISSUE TITLE
Source code PDF generator

### ISSUE THREAD

**Issue by dieram3** [dieram3/competitive-programming-library#15]
We need a script to generate a resume of the library. So it could be easily printed to compete.

**Comment by jaguirresza** [comment]
I have an a simple idea that might work, why we don't just use Markdown with a simple keywords, maybe we can use the same as doxygen. The idea it's simple, this is an example: (only function with `@function`keyword goes to the generated file)

`````` c++

/// @function foo
/// @brief foo evaluates `a` in `bar`.
/// @details Here we can use normal markdown :)
/// `bar` must follow the next signature:
//// ````c++
//// int f(float);
//// ````
//// @returns `bar(a)`
template<Func fn>
int foo(float a, Func &&bar) { return bar(a); }
``````

This its easily transform to

``````
# foo
**Brief** foo evaluates `a` in `bar`.
**Details** here we can use normal markdown :)
`bar` must follow the next signature:
````c++
 int f(float);
 ````
**Returns** `bar(a)`
````c++
template<Func fn>
int foo(float a, Func &&bar) { return bar(a); }
````
``````

## And that looks like this:

# foo

**Brief** foo evaluates `a` in `bar`.
**Details** here we can use normal markdown :)
`bar` must follow the next signature:

``` c++
 int f(float);
```

**Returns** `bar(a)`

``` c++
template<Func fn>
int foo(float a, Func &&bar) { return bar(a); }
```

**Comment by jaguirresza** [comment]
And then just use [pandoc](http://pandoc.org) to generate the `pdf`file.

**Comment by dieram3** [comment]
mm it's fine but... would we have to write documentation in a mix of markdown and doxygen?

**Comment by jaguirresza** [comment]
mmm yes, but `doxygen` has some markdown support

**Comment by jaguirresza** [comment]
that's the other thing maybe we don't need `doxygen` at all, given the purpose of the library. Whats would be the benefit to expose the API, hiding the implementation of the algorithms? I think the implementation it's what someone wants to see, so the format proposed above might be the correct approach of documentation.

**Comment by dieram3** [comment]
Ok, you're right. Let's do it that.

**Comment by dieram3** [comment]
This problem is solved. But can be improved...
