### ISSUE TITLE
Point 2D class

### ISSUE THREAD

**Issue by dieram3** [dieram3/competitive-programming-library#21]
I have recently seen the future point class.

I leave my comments below:

1) Scalar multiplication and division should not be templated, instead use T as the scalar type.

``` C++
  friend point operator*(const point &p, const T &k) {
    return {p.x * k, p.y * k};
  }

  friend point operator/(const point &p, const T &k) {
    return {p.x / k, p.y / k};
  }
```

 otherwise all other operators should allow mixing different underlying types and return the common type.

2) Left scalar multiplication is missing
Add

``` C++
  friend point operator*( const T &k, const point &p) {
    return p * k;
  }
```

3) 'norm' and 'distance' should return T or a deduced type, for example

``` C++
 friend auto norm(const point &p) -> decltype(std::sqrt(norm2(p))) { 
   return std::sqrt(norm2(p));
 } 
```

Someone could instantiate the class with long double and  should not modify this code.

4) distance2 should return T not double

``` C++
friend T distance2(const point &p, const point &q) {
    return norm2(p - q);
 }
```

5) should not stream operator print a comma and a space in the middle instead of a single white space?

``` C++
friend std::ostream &operator<<(std::ostream &os, const point &p) {
    os << '(' << p.x << ", " << p.y << ')';
    return os;
  }
```

6) Greater than operator should be implemented as:

``` C++
friend bool operator>(const point &p, const point &q) {
    return q < p;
  }
```

I have not yet reviewed clockwise related functions but should not they be in a different file?

**Comment by jaguirresza** [comment]
This is just a backup... I need to format my PC

**Comment by jaguirresza** [comment]
I look everything now, and actually all changes are correct and are implemented now :)

**Comment by dieram3** [comment]
Done
