### ISSUE TITLE
Adds Float class

### ISSUE THREAD

**Issue by jaguirresza** [dieram3/competitive-programming-library#9]
We need to upload Float class for easy comparison with floating points numbers.

**Comment by dieram3** [comment]
The class 'efloat' was removed from this repo, because it can cause ambiguity. There are many ways of doing comparisons. I think it is best having comparison functions like almost_equal.

**Comment by jaguirresza** [comment]
Ok, then i will just add `almost_equal` function

**Comment by dieram3** [comment]
Ok, that's fine.

**Comment by dieram3** [comment]
Wait, now I think, the almost_equal function is not so necessary. First, it is intuitive to implement. Second, it could be very dependent of the case. I propose not to integrate this function and close this issue (at least until we have a good reason).
